exports.blocks = [
    { "name": "page" },
    { "name": "text" },
    { "name": "grid" },
    { "name": "colors" },
    { "name": "header" },
    { "name": "logo" },
    { "name": "hamburger" },
    { "name": "button" },
    { "name": "hero" },
    { "name": "about" },
    { "name": "adaptiveImg" },
    { "name": "howWorks" },
    { "name": "ticker" },
    { "name": "stats" },
    { "name": "cards" },
    { "name": "brand" },
    { "name": "socials" },
    { "name": "footer" },
    { "name": "modal" },
    { "name": "form" },
    { "name": "contact" },
    { "name": "thankYou" }
];
